services:
  app:
    build: .
    image: paraview-user
    container_name: paraview-user
    tty: true
    restart: always
    privileged: true
    runtime: nvidia
    user: 1000:1000
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
      - ${HOME}/workspace:/home/developer/workspace
